//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMS_News()
        {
            this.CMS_Approves = new HashSet<CMS_Approves>();
        }
    
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string EXCERPT { get; set; }
        public string CONTENTS { get; set; }
        public string PICTURE { get; set; }
        public Nullable<int> ID_USERCREATE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<short> ID_CATEGORIES { get; set; }
        public Nullable<short> ID_NEWS_STATUS { get; set; }
        public Nullable<int> NUMBEROFVIEW { get; set; }
        public Nullable<int> ID_USERMODIFY { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<short> ISFOCUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMS_Approves> CMS_Approves { get; set; }
        public virtual CMS_Categories CMS_Categories { get; set; }
        public virtual CMS_News_Status CMS_News_Status { get; set; }
        public virtual CSF_Users CSF_Users { get; set; }
    }
}
