//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Questions
    {
        public int ID { get; set; }
        public Nullable<short> TypeOfQuestionID { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> Publish { get; set; }
        public Nullable<int> UserCreate { get; set; }
    
        public virtual CMS_TypeOfQuestion CMS_TypeOfQuestion { get; set; }
    }
}
