//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_MapService
    {
        public int ID { get; set; }
        public int MapID { get; set; }
        public int ServiceID { get; set; }
        public short Orders { get; set; }
    
        public virtual CMS_Maps CMS_Maps { get; set; }
        public virtual CMS_Services CMS_Services { get; set; }
    }
}
