//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMS_Services()
        {
            this.CMS_MapService = new HashSet<CMS_MapService>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Publish { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public string XMin { get; set; }
        public string YMin { get; set; }
        public string XMax { get; set; }
        public string YMax { get; set; }
        public Nullable<int> TypeOfMapID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMS_MapService> CMS_MapService { get; set; }
        public virtual CMS_TypeOfMap CMS_TypeOfMap { get; set; }
    }
}
