//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSF_HCXa
    {
        public int ID { get; set; }
        public string MaPhuongXa { get; set; }
        public string TenPhuongXa { get; set; }
        public string TenTiengAnh { get; set; }
        public string Cap { get; set; }
        public string MaQuanHuyen { get; set; }
        public string TenQuanHuyen { get; set; }
        public string MaTinh { get; set; }
        public string TenTinh { get; set; }
        public string MoTa { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual CSF_HCHuyen CSF_HCHuyen { get; set; }
    }
}
