//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSF_Pages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CSF_Pages()
        {
            this.CSF_PagePartial = new HashSet<CSF_PagePartial>();
            this.CSF_PageRole = new HashSet<CSF_PageRole>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Key { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Order { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> IsBlank { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsHost { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSF_PagePartial> CSF_PagePartial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSF_PageRole> CSF_PageRole { get; set; }
    }
}
