//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSF_HCHuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CSF_HCHuyen()
        {
            this.CSF_HCXa = new HashSet<CSF_HCXa>();
        }
    
        public int ID { get; set; }
        public string MaQuanHuyen { get; set; }
        public string TenQuanHuyen { get; set; }
        public string TenTiengAnh { get; set; }
        public string Cap { get; set; }
        public string MaTinh { get; set; }
        public string TenTinh { get; set; }
        public string MoTa { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual CSF_HCTinh CSF_HCTinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSF_HCXa> CSF_HCXa { get; set; }
    }
}
