//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSF_PagePartial
    {
        public int ID { get; set; }
        public int PageID { get; set; }
        public int PartialID { get; set; }
        public string Title { get; set; }
        public string Position { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsBox { get; set; }
        public Nullable<int> BoxParent { get; set; }
    
        public virtual CSF_Pages CSF_Pages { get; set; }
        public virtual CSF_Partials CSF_Partials { get; set; }
    }
}
