//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSF_Templates
    {
        public int ID { get; set; }
        public string logo { get; set; }
        public string background_header { get; set; }
        public string style { get; set; }
        public string primary_title { get; set; }
        public string secondary_title { get; set; }
    }
}
