//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSF_Partials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CSF_Partials()
        {
            this.CSF_PagePartial = new HashSet<CSF_PagePartial>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Key { get; set; }
        public int ModuleID { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Controller { get; set; }
    
        public virtual CSF_Modules CSF_Modules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSF_PagePartial> CSF_PagePartial { get; set; }
    }
}
